- name: Money laundering demo
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/settings/local/settings.yml
    - vars/vertices/accounts.yml
    - vars/edges/transactions.yml

  tasks:    
    - name: cleanup graph database      
      ansible.builtin.include_tasks: tasks/database/database.yml

    - name: unique key for banking
      platform42.neo4j.constraint:
        neo4j_uri: "{{ NEO4J_URI }}"
        database: "{{ NEO4J_DATABASE }}"
        username: "{{ NEO4J_USERNAME }}"
        password: "{{ NEO4J_PASSWORD }}"
        label: Account
        property: entity_name
      register: constraint

    - name: 
      ansible.builtin.debug:
        var: constraint      

    - name: create banking accounts
      ansible.builtin.include_tasks: tasks/vertices/accounts.yml
      loop: "{{ accounts }}"
      
    - name: create banking transactions
      ansible.builtin.include_tasks: tasks/edges/transactions.yml
      loop: "{{ transactions }}"
      
