- name: Query all cycles
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/settings/local/settings.yml

  tasks:
    - name: detect cycle_candidates     
      ansible.builtin.include_tasks: tasks/detect/cycle_candidates/query.yml

    - name: detect fast_cycles      
      ansible.builtin.include_tasks: tasks/detect/cycle_fast/loop.yml


