- name: Query all cycles
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/settings/local/settings.yml

  tasks:
    - name: "Phase I - detect cycle_candidates"     
      ansible.builtin.include_tasks: tasks/detect/010-cycle_candidates/query.yml

    - name: "Phase II - detect fast_cycles"     
      ansible.builtin.include_tasks: tasks/detect/020-cycle_fast/loop.yml

    - name: "Phase III - Detect repeated or frequent cycles"
      ansible.builtin.include_tasks: tasks/detect/030-cycle_frequent/loop.yml

    - name:
      ansible.builtin.debug:
        var: cycle_paths_phase_3