- name: Query all cycles
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/settings/local/settings.yml

  tasks:
    - name: all cycles
      platform42.neo4j.query_read:
        neo4j_uri: "{{ NEO4J_URI }}"
        database: "{{ NEO4J_DATABASE }}"
        username: "{{ NEO4J_USERNAME }}"
        password: "{{ NEO4J_PASSWORD }}"
        query: >
          MATCH path = (account:Account)-[:TRANSACTION*2..6]->(account)
          WITH
            account,
            path,
            [accountNode IN nodes(path) | accountNode.id] AS cycleAccounts,
            length(path) AS hops,
            reduce(total = 0, transaction IN relationships(path) | total + transaction.amount) AS totalTransferred
          RETURN
            account.id AS startAccount,
            cycleAccounts,
            hops,
            totalTransferred
          ORDER BY totalTransferred DESC;
      register: data

    - name: print
      ansible.builtin.debug:
        var: data.query_read.cypher_response



      
