---
- name: create unique key on entity_name
  platform42.neo4j.constraint:
    neo4j_uri: "{{ NEO4J_URI }}"
    database: "{{ NEO4J_DATABASE }}"
    username: "{{ NEO4J_USERNAME }}"
    password: "{{ NEO4J_PASSWORD }}"
    label: Account
    property: entity_name
    state: PRESENT
  register: entity_name

- name: print entity_name constraint
  ansible.builtin.debug:
    var: entity_name.constraint

