---
- name: "fast query"
  platform42.neo4j.query_read:
    neo4j_uri: "{{ NEO4J_URI }}"
    database: "{{ NEO4J_DATABASE }}"
    username: "{{ NEO4J_USERNAME }}"
    password: "{{ NEO4J_PASSWORD }}"
    query: |
      MATCH p=(a:Account)-[:TRANSACTION*2..6]->(a)
      WITH 
        a.id AS startAccount,
        [x IN nodes(p) | x.id] AS cyclePath,
        length(p) AS hops,
        reduce(total=0, r IN relationships(p) | total + r.amount) AS totalAmount
      RETURN
        startAccount,
        cyclePath,
        hops,
        totalAmount
      ORDER BY totalAmount DESC;
            ;
    parameters:
      nodeIds: "{{ item.cyclePath }}"
  register: cycle_fast_output

- name: print
  ansible.builtin.debug:
    var: cycle_fast_output