---
- name: all_cycles
  ansible.builtin.set_fact: 
    cycle_fast_input: "{{ cycle_candidates_output.query_read.cypher_response }}"

- name: "Detect fast cycles within previously detected cycles"
  ansible.builtin.include_tasks: tasks/detect/020-inner-cycle_fast.yml
  loop: "{{ cycle_fast_input}}"
  loop_control:
    label: "{{ item.startAccount }}"
