---
- name: "output item"
  ansible.builtin.debug:
    var: item

- name: "fast query"
  platform42.neo4j.query_read:
    neo4j_uri: "{{ NEO4J_URI }}"
    database: "{{ NEO4J_DATABASE }}"
    username: "{{ NEO4J_USERNAME }}"
    password: "{{ NEO4J_PASSWORD }}"
    query: |
      MATCH p=(a:Account)-[r:TRANSACTION*2..6]->(a)
      WHERE all(n IN nodes(p) WHERE n.id IN $nodeIds)
      WITH 
        a.id AS startAccount,
        [x IN nodes(p) | x.id] AS cyclePath,
        [rel IN relationships(p) | datetime(rel.timestamp)] AS times,
        length(p) AS hops,
        reduce(total=0, rel IN relationships(p) | total + rel.amount) AS totalAmount
      WITH 
        startAccount,
        cyclePath,
        hops,
        totalAmount,
        reduce(minT = head(times), t IN times | CASE WHEN t < minT THEN t ELSE minT END) AS minTime,
        reduce(maxT = head(times), t IN times | CASE WHEN t > maxT THEN t ELSE maxT END) AS maxTime
      WHERE duration.between(minTime, maxTime).days <= 3
      RETURN 
        startAccount,
        cyclePath,
        hops,
        totalAmount,
        minTime,
        maxTime,
        duration.between(minTime, maxTime).days AS durationDays
      ORDER BY totalAmount DESC;
    parameters:
      nodeIds: "{{ item.cyclePath }}"
  register: cycle_fast_output

- name: print
  ansible.builtin.debug:
    var: cycle_fast_output.query_read.cypher_query_inline