--- 
- name: "Find repeated cycles for {{ item.startAccount }}"
  platform42.neo4j.query_read:
    neo4j_uri: "{{ NEO4J_URI }}"
    database: "{{ NEO4J_DATABASE }}"
    username: "{{ NEO4J_USERNAME }}"
    password: "{{ NEO4J_PASSWORD }}"
    query: |
      MATCH p=(a:Account)-[:TRANSACTION*2..6]->(a)
      WHERE [x IN nodes(p) | x.entity_name] = $nodeIds
      WITH 
        p, 
        [x IN nodes(p) | x.entity_name] AS cyclePath
      UNWIND 
        relationships(p) AS rel
      WITH 
        cyclePath, 
        collect(DISTINCT date(datetime(rel.timestamp))) AS days,
        count(DISTINCT p) AS occurrences,
        sum(rel.amount) AS totalAmount
      RETURN 
        cyclePath, 
        occurrences, 
        size(days) AS distinctDays, 
        totalAmount
      ORDER BY occurrences DESC
    parameters:
      nodeIds: "{{ item.cyclePath }}"
  register: cycle_path

- name: "Capture output"
  ansible.builtin.set_fact:
    cycle_path_phase_3: "{{ cycle_path.query_read.cypher_response }}"

- name: "Print captured output"
  ansible.builtin.debug:
    var: cycle_path_phase_3.cyclePath

- name: "Append captured output"
  set_fact:
    cycle_paths_phase_3: "{{ (cycle_paths_phase_3 | default([])) + cycle_path_phase_3 }}"
  when: 
    - cycle_path_phase_3 is defined 
    - cycle_path_phase_3 | length > 0
