---
- name: Build list of suspect nodes
  ansible.builtin.set_fact:
    suspect_nodes: >-
      {{ item
       | selectattr('occurrences', '>', 2)
       | selectattr('totalAmount', '>', 10000)
       | map(attribute='cyclePath')
       | flatten
       | unique
       | list 
       }}

- name: "iterator"
  ansible.builtin.debug:
    var: suspect_nodes

- name: Label each suspect node individually
  platform42.neo4j.label:
    neo4j_uri: "{{ NEO4J_URI }}"
    database: "{{ NEO4J_DATABASE }}"
    username: "{{ NEO4J_USERNAME }}"
    password: "{{ NEO4J_PASSWORD }}"
    base_label: Account
    entity_name: "{{ item }}"
    label: Suspect
    state: PRESENT
  loop: "{{ suspect_nodes}}"
