---
- name: Build list of nodes from this cyclePath
  set_fact:
    suspect_nodes: "{{ item.cyclePath | flatten }}"

- name: Label each node in the current suspect cycle
  platform42.neo4j.label:
    neo4j_uri: "{{ NEO4J_URI }}"
    database: "{{ NEO4J_DATABASE }}"
    username: "{{ NEO4J_USERNAME }}"
    password: "{{ NEO4J_PASSWORD }}"
    base_label: Account
    entity_name: "{{ item_node }}"
    label: Suspect
    state: PRESENT
  loop: "{{ suspect_nodes }}"
  loop_control:
    loop_var: item_node
  when: 
    - suspect_nodes | length > 0
